### ISSUE TITLE
rhc app create  owncloud php-5.4 mysql-5.5 cron-1.4 

### ISSUE THREAD

**Issue by TwistingTwists** [openshift/owncloud-openshift-quickstart#26]
Update in `README.md` .
It is ```rhc create-app owncloud php-5.4 mysql-5.5 cron-1.4``` 

rhc app create causes following error.

```Error communicating with DNS system (Login Failed). Please try again and contact support if the issue persists.```

**Comment by bparees** [comment]
rhc app create and rhc create-app are synonymous, any issue you hit with one and not the other was unrelated to the invocation.  I was able to successfully create the app using the "rhc app create" invocation.
